const cotizaciones = [
  {
    COD_SIMB: 'ABC.A',
    DESC_SIMB: 'BANCO DEL CARIBE,C.A.BCO.UNIV.CLASE (A)',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: '20.99',
    VOL_VTA_1: '104',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'ALZ.B',
    DESC_SIMB: 'ALALZA INVERSIONES, C.A. CLASE "B"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'ARC.A',
    DESC_SIMB: 'ARCA INM. Y VALORES, C.A. CLASE "A"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'ARC.B',
    DESC_SIMB: 'ARCA INM. Y VALORES, C.A. CLASE "B"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: '33',
    VOL_VTA_1: '390',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'BNC',
    DESC_SIMB: 'BANCO NACIONAL DE CREDITO,C.A.BCO.UNIV.',
    VOL_CMP_1: '138',
    PRE_CMP_1: '.0245',
    PRE_VTA_1: '.0275',
    VOL_VTA_1: '1053',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'BNC.O',
    DESC_SIMB: 'BANCO NACIONAL DE CREDITO,C.A.BCO.UNIV.',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'BPV',
    DESC_SIMB: 'BANCO PROVINCIAL, S.A. BCO. UNIVERSAL',
    VOL_CMP_1: '2000',
    PRE_CMP_1: '8',
    PRE_VTA_1: '8.88',
    VOL_VTA_1: '450',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'BVCC',
    DESC_SIMB: 'BOLSA DE VALORES DE CARACAS, C.A.',
    VOL_CMP_1: '64',
    PRE_CMP_1: '2.75',
    PRE_VTA_1: '3',
    VOL_VTA_1: '6480',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'BVL',
    DESC_SIMB: 'BANCO DE VENEZUELA, S.A. BCO.UNIVERSAL',
    VOL_CMP_1: '6200',
    PRE_CMP_1: '3.41',
    PRE_VTA_1: '4.25',
    VOL_VTA_1: '2000',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'CCR',
    DESC_SIMB: 'CERAMICA CARABOBO, SACA',
    VOL_CMP_1: '1',
    PRE_CMP_1: '161',
    PRE_VTA_1: '219',
    VOL_VTA_1: '25',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'CGQ',
    DESC_SIMB: 'CORP.GRUPO QUIMICO, C.A.',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'CIE',
    DESC_SIMB: 'CORP. INDUSTRIAL DE ENERGIA CA SACA',
    VOL_CMP_1: '2',
    PRE_CMP_1: '.14',
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'CIE.O',
    DESC_SIMB: 'CORP. INDUSTRIAL DE ENERGIA CA SACA',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'CRM.A',
    DESC_SIMB: 'CORIMON, C.A.',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'DOM',
    DESC_SIMB: 'DOMINGUEZ & CIA., S.A.',
    VOL_CMP_1: '2000',
    PRE_CMP_1: '7',
    PRE_VTA_1: '8.49',
    VOL_VTA_1: '576',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'EFE',
    DESC_SIMB: 'PRODUCTOS EFE S.A.',
    VOL_CMP_1: '500',
    PRE_CMP_1: '1.15',
    PRE_VTA_1: '1.39',
    VOL_VTA_1: '599',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'ENV',
    DESC_SIMB: 'ENVASES VENEZOLANOS S.A.',
    VOL_CMP_1: '369',
    PRE_CMP_1: '10.19',
    PRE_VTA_1: '10.29',
    VOL_VTA_1: '58',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'FFV.A',
    DESC_SIMB: 'FIVENCA FONDO CAPITAL PRIVADO. CLASE "A"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'FFV.B',
    DESC_SIMB: 'FIVENCA FONDO CAPITAL PRIVADO. CLASE "B"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'FNC',
    DESC_SIMB: 'FABRICA NACIONAL DE CEMENTOS, C.A.',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'FVI.A',
    DESC_SIMB: 'FONDO DE VALORES INMOB.,SACA. CLASE (A)',
    VOL_CMP_1: '13',
    PRE_CMP_1: '28',
    PRE_VTA_1: '31.95',
    VOL_VTA_1: '79',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'FVI.B',
    DESC_SIMB: 'FONDO DE VALORES INMOB.,SACA. CLASE (B)',
    VOL_CMP_1: '500',
    PRE_CMP_1: '7.05',
    PRE_VTA_1: '8',
    VOL_VTA_1: '415',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'GZL',
    DESC_SIMB: 'GRUPO ZULIANO, C.A.',
    VOL_CMP_1: '135',
    PRE_CMP_1: '13.61',
    PRE_VTA_1: '20.3',
    VOL_VTA_1: '223',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'GZL.A',
    DESC_SIMB: 'GRUPO ZULIANO, PREF. CLASE "A"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'GZL.B',
    DESC_SIMB: 'GRUPO ZULIANO, PREF. CLASE " B"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'ICP.B',
    DESC_SIMB: 'INVERSIONES CRECEPYMES, C.A. CLASE "B"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: '15.69',
    VOL_VTA_1: '37',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'IMP.B',
    DESC_SIMB: 'IMPULSA AGRONEGOCIOS, C.A. CLASE "B"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'IVC',
    DESC_SIMB: 'INVACA,INMUEBLES,VALORES Y CAPITALES,',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: '17.35',
    VOL_VTA_1: '68',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'MPA',
    DESC_SIMB: 'MANUFACTURAS DE PAPEL,C.A.(MANPA) SACA.',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: '1.42',
    VOL_VTA_1: '793',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'MTC.B',
    DESC_SIMB: 'MONTESCO FONDO AGROINDUSTRIAL  CLASE "B"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'MVZ.A',
    DESC_SIMB: 'MERCANTIL SERV. FINANCIEROS C.A. CLS.(A)',
    VOL_CMP_1: '300',
    PRE_CMP_1: '40',
    PRE_VTA_1: '49.95',
    VOL_VTA_1: '633',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'MVZ.B',
    DESC_SIMB: 'MERCANTIL SERV. FINANCIEROS C.A. CLS.(B)',
    VOL_CMP_1: '333',
    PRE_CMP_1: '38',
    PRE_VTA_1: '45',
    VOL_VTA_1: '500',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'OCE',
    DESC_SIMB: 'ORIENTE ENTIDAD DE INV.COL.INM.,C.A.',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'PER',
    DESC_SIMB: 'PC-IBC FONDO MUTUAL DE INV. CAP. CERRADO',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'PGR',
    DESC_SIMB: 'PROAGRO C.A.',
    VOL_CMP_1: '560',
    PRE_CMP_1: '.554',
    PRE_VTA_1: '.559',
    VOL_VTA_1: '90',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'PGR.O',
    DESC_SIMB: 'PROAGRO C.A.  (SESION ESPECIAL)',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'PIV.A',
    DESC_SIMB: 'PIVCA PROMOTRA  INV. Y VALORES CLASE "A"',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'PIV.B',
    DESC_SIMB: 'PIVCA PROMOTRA  INV. Y VALORES CLASE "B"',
    VOL_CMP_1: '45',
    PRE_CMP_1: '280',
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'PTN',
    DESC_SIMB: 'PROTINAL C.A.',
    VOL_CMP_1: '2190',
    PRE_CMP_1: '2.3',
    PRE_VTA_1: '3',
    VOL_VTA_1: '290',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'RST',
    DESC_SIMB: 'C.A. RON SANTA TERESA',
    VOL_CMP_1: '20',
    PRE_CMP_1: '4.7',
    PRE_VTA_1: '5',
    VOL_VTA_1: '1000',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'RST.B',
    DESC_SIMB: 'C.A. RON SANTA TERESA (CLASE B)',
    VOL_CMP_1: '1000',
    PRE_CMP_1: '2.45',
    PRE_VTA_1: '2.86',
    VOL_VTA_1: '675',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'SVS',
    DESC_SIMB: 'SIVENSA, S.A',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: '3.5',
    VOL_VTA_1: '660',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'TDV.D',
    DESC_SIMB: 'C.A.NAC.TELF.VZLA. (CANTV) CLASE (D)',
    VOL_CMP_1: '500',
    PRE_CMP_1: '2.8',
    PRE_VTA_1: '3.48',
    VOL_VTA_1: '1091',
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'TPG',
    DESC_SIMB: 'C.A. TELARES DE PALO GRANDE',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
  {
    COD_SIMB: 'TPG.O',
    DESC_SIMB: 'C.A. TELARES DE PALO GRANDE',
    VOL_CMP_1: null,
    PRE_CMP_1: null,
    PRE_VTA_1: null,
    VOL_VTA_1: null,
    CANT_NEGOC_DES: '0',
  },
];

console.log(cotizaciones.length);
